### PR TITLE
Addcommand alpha bug fixes

### LINKED ISSUE #162: bug fix: add command saves job as upper and lower case separately

### LINKED ISSUE #178: bug fix: Add command fails to check for duplicates
- Add command only checks for name duplicate
- Error message when duplicated person added does not appear

### PR DESCRIPTION
**Pull request by zzibo**
fixes #162 
fixes #178

### CODE REVIEW

File: src/main/java/seedu/address/logic/commands/DeleteYCommand.java [hunk 1]
```diff
@@ -89,7 +90,7 @@ public CommandResult execute(Model model) throws CommandException {
             model.deletePerson(personToDelete);
             // Clear history of personToDelete from StaticContext once delete operation is done
             StaticContext.setPersonToDelete(null);
-            return new CommandResult(String.format(MESSAGE_DELETE_PERSON_SUCCESS, personToDelete));
+            return new CommandResult(String.format(MESSAGE_DELETE_PERSON_SUCCESS, Messages.format(personToDelete)));
```
Comment (jonushzw) [inline src/main/java/seedu/address/logic/commands/DeleteYCommand.java:93]: great job using this method, if not it would have been obsolete!

File: src/main/java/seedu/address/model/person/Job.java [hunk 2]
```diff
@@ -61,4 +61,20 @@ public boolean equals(Object other) {
...
+     * @return a string of job title with each word capitalised
+     */
+    public String capitaliseJob(String job) {
+        String capitalisedJob = "";
+        String[] words = job.toLowerCase().split(" ");
+        for (String word : words) {
+            capitalisedJob += Character.toUpperCase(word.charAt(0)) + word.substring(1) + " ";
+        }
+        return capitalisedJob.trim();
+    }
```
Comment (jonushzw) [inline src/main/java/seedu/address/model/person/Job.java:79]: easy way to standardise input in the json file 👍

File: src/main/java/seedu/address/model/person/Name.java [hunk 3]
```diff
@@ -64,4 +65,21 @@ public int hashCode() {
...
+    public String capitaliseName(String name) {
+        String capitalisedName = "";
+        String[] words = name.toLowerCase().split(" ");
+        for (String word : words) {
+            if (!word.isEmpty()) {
+                capitalisedName += Character.toUpperCase(word.charAt(0)) + word.substring(1) + " ";
+            }
+        }
+        return capitalisedName.trim();
+    }
```
Comment (jonushzw) [inline src/main/java/seedu/address/model/person/Name.java:84]: same as job class 👍

**Review by jonushzw — COMMENTED** [review]
LGTM!
