### PR TITLE
bug fix: Delete Command now removes Person from Wedding

### LINKED ISSUE #168: bug fix: Job field not capitalised

### LINKED ISSUE #191: bug fix: DeleteCommand does not remove person from wedding

### PR DESCRIPTION
**Pull request by zzibo**
fixes #168 
fixes #191

### CODE REVIEW

File: src/main/java/seedu/address/logic/commands/TagDeleteCommand.java [hunk 1]
```diff
@@ -142,71 +139,9 @@ private String generateDeleteMessage(Person personToEdit, Person editedPerson, M
             }
         }
 
-        deletePersonInWedding(editedPerson, model, tagsToDelete);
+        model.deletePersonInWedding(editedPerson, model, tagsToDelete);
         return String.format(MESSAGE_DELETE_TAG_SUCCESS, Messages.tagSetToString(tagsToDelete),
                 Messages.format(editedPerson), Messages.format(editedPerson),
                 Messages.tagSetToString(tagsToDelete));
     }
-
```
Comment (yastsc) [inline src/main/java/seedu/address/logic/commands/TagDeleteCommand.java:150]: Good job moving these methods to Model & ModelManager! Can I check if this has been done for TagAddCommand as well? I think it has setPersonInWedding, updatePersonInWedding and getWeddingFromTags, which should all be transferred to Model & ModelManager as well

File: src/main/java/seedu/address/model/ModelManager.java [hunk 2]
```diff
@@ -245,4 +252,84 @@ public boolean equals(Object other) {
...
+            set.remove(editedPerson);
+        }
+    }
+    /**
+     * Removes all tags from a person and removes the person from any weddings related to those tags.
+     *
+     * @param personToEdit the person whose tags will be removed.
+     * @param model        the current model containing the necessary wedding address book.
+     */
+    public Person personWithAllTagsRemoved(Person personToEdit, Model model) {
```
Comment (yastsc) [inline src/main/java/seedu/address/model/ModelManager.java:324]: Logic makes sense here 👍

**Review by yastsc — COMMENTED** [review]
Just need to move some methods in TagAddCommand to Model & ModelManager as well for consistency, but overall logic LGTM!
